name: Build, Push Docker image to Docker Hub and Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: quarwork/simple-docker-ci-app:latest

    - name: Check if Fly app exists
      id: check_app
      run: |
        if flyctl apps list | grep -q simple-docker-ci-app; then
          echo "app_exists=true" >> $GITHUB_OUTPUT
        else
          echo "app_exists=false" >> $GITHUB_OUTPUT
        fi
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    - name: Create Fly app if missing
      if: steps.check_app.outputs.app_exists == 'false'
      run: flyctl apps create simple-docker-ci-app --region fra
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    - name: Deploy to Fly.io
      uses: superfly/flyctl-actions@1.4
      with:
        args: "deploy --remote-only --app simple-docker-ci-app"
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}