name: Build and Push Docker image to Docker Hub and Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: quarwork/simple-docker-ci-app:latest

    - name: Check if Fly app exists
      uses: superfly/flyctl-actions@1.4
      id: check_app
      with:
        args: "apps show simple-docker-ci-app"
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      continue-on-error: true

    - name: Create Fly app if missing
      if: steps.check_app.outcome == 'failure'
      uses: superfly/flyctl-actions@1.4
      with:
        args: "apps create simple-docker-ci-app --region fra"
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    - name: Deploy to Fly.io
      uses: superfly/flyctl-actions@1.4
      with:
        args: "deploy --remote-only --app simple-docker-ci-app"
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}